name: Multilingual Example CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - run: npx skir format --ci
      # - run: npx skir snapshot --ci

      # # 1. Regenerate Skir code
      # - name: Skir Gen
      #   run: npx skir gen

      # 3. Check Frontend (TypeScript)
      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install && npm run build

      # 2. Check Backend (Python)
      - name: Install Python dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Backend syntax
        working-directory: backend
        run: python3 -m py_compile server.py

      - name: Lint Backend
        working-directory: backend
        run: flake8 --exclude venv,skirout .

      # - name: Build Frontend
      #   working-directory: frontend
      #   run: npm run build
